;; Function keys
(global-set-key [f1] 'manual-entry)
(global-set-key [f2] 'info)
;;(global-set-key [f3] 'repeat-complex-command)
(global-set-key [f4] 'vim-mode)
(global-set-key [f5] 'eval-current-buffer)
(global-set-key [f6] 'buffer-menu)
(global-set-key [f7] 'other-window)
(global-set-key [f8] 'find-file)
(global-set-key [f9] 'save-buffer)
(global-set-key [f10] 'next-error)
(global-set-key [f11] 'compile)
(global-set-key [f12] 'grep)
(global-set-key [C-f1] 'compile)
;;(global-set-key [C-f2] 'grep)
;;(global-set-key [C-f3] 'next-error)
(global-set-key [C-f4] 'previous-error)
(global-set-key [C-f5] 'display-faces)
(global-set-key [C-f8] 'dired)
(global-set-key [C-f10] 'kill-compilation)

;; Meta
;(global-set-key "\M- " 'set-mark-command)
(global-set-key "\M-\C-h" 'backward-kill-word)
(global-set-key "\M-\C-r" 'query-replace)
(global-set-key "\M-r" 'replace-string)
(global-set-key "\M-g" 'goto-line)
;(global-set-key "\M-h" 'help-command)
(global-set-key [C-tab] "\C-q\t")  ; Control-tab quotes a tab
