;; Function keys
(global-set-key [f1] 'manual-entry)
(global-set-key [f2] 'info)
;;(global-set-key [f3] 'repeat-complex-command)
(global-set-key [f4] 'vim-mode)
(global-set-key [f5] 'gud-cont)
(global-set-key [f6] 'gdb-many-windows)
(global-set-key [f7] 'other-window)
(global-set-key [f8] 'gud-until)
(global-set-key [f9] 'gud-tbreak)
(global-set-key [f10] 'gud-next)
(global-set-key [f11] 'gud-step)
(global-set-key [f12] 'find-dired)
;;(global-set-key [C-f1] 'compile)
;;(global-set-key [C-f2] 'grep)
;;(global-set-key [C-f3] 'next-error)
;;(global-set-key [C-f4] 'previous-error)
;;(global-set-key [C-f5] 'display-faces)
;;(global-set-key [C-f8] 'dired)
;;(global-set-key [C-f10] 'kill-compilation)
(global-set-key [C-f11] 'gud-finish)
(global-set-key [C-f12] 'rgrep)


