(require 'session)
(add-hook 'after-init-hook 'session-initialize)
(load "desktop") 
(desktop-load-default) 
(desktop-read)
(require 'ibuffer)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(require 'ido)
(ido-mode t)
(setq ido-everywhere t)
(setq ido-enable-flex-matching t)
(setq ido-confirm-unique-completion nil)
;(require 'tabbar)
;(tabbar-mode)
;(global-set-key (kbd "C-x ,") 'tabbar-backward)
;(global-set-key (kbd "C-x .") 'tabbar-forward)
(require 'setnu+)
(global-set-key (kbd "C-x n") 'setnu-mode)

;(global-set-key [(control f3)] 'highlight-symbol-at-point)
;(global-set-key [f3] 'highlight-symbol-next)
;(global-set-key [(shift f3)] 'highlight-symbol-prev)
;;(global-set-key [(meta f3)] 'highlight-symbol-prev)))

(when (not (eq system-type 'usg-unix-v))
;; vim-mode
(add-to-list 'load-path "~/.emacs.d/lyro-vim-mode-tip")
(require 'vim)
)