#!/bin/bash -eu
# local bash settings

echo Sourcing user bashrc ...

pathmunge () {
	if ! echo $PATH | /bin/egrep "(^|:)$1($|:)" >/dev/null ; then
	   if [ "$2" = "after" ] ; then
	      PATH=$PATH:$1
	   else
	      PATH=$1:$PATH
	   fi
	fi
}

cdn () { pushd .; for ((i=1; i<=$1; i++)); do cd ..; done; }

ctitle() {
    echo -ne "\033]0;$1\007"
}

[ $OS ] || OS=$(uname)

stty -ixon #-ixoff

# history
export HISTIGNORE=".1:.2:.3:.4:pwd:ls:l:la:ll:exit:quit:h:w:who:whoami:alias:which*:whereis*:cd:python*:emacs*:eclipse*:ps:v:vi:vim:envhost*:hostname:make:pstack*:pstree*:ifconfig*:jobs:fg:bg*:cal:date:locate:sleep*"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=1000
export HISTFILESIZE=5000

# extended globbing
shopt -s extglob

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Color definitions
COLORRC=$(dirname ${BASH_SOURCE[0]})/color.rc
[ -f $COLORRC ] && . $COLORRC

##################################
# prompt
#export PS1='\n=== \h [\D{%m-%d %a %H:%M:%S}] \w ===\n$ '
PS1="\n=\!=${Green}[\d \@] ${BIYellow}\u@\h:${White}\w\e[m ===\n\$ "


#########################################
# OS specific settings
#########################################
if [ $OS = SunOS ]; then
PATH=${PATH:+$PATH:}/usr/local/bin:/usr/ucb:/usr/openwin/bin:/usr/sfw/bin:/usr/ccs/bin:/usr/dt/bin${MRM_BIN:+:$MRM_BIN}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/openwin/lib:/usr/lib/X11:/usr/dt/lib:/usr/sfw/lib:/usr/ccs/lib:/usr/local/lib

# system limit
ulimit -S -c unlimited >&-

# man path
export MANPATH=/usr/share/man:/usr/sfw/man:/usr/man:/usr/openwin/man:/apps/gnu/man:/apps/algo/perl/man

elif [ "$OS" = Linux ]; then
# User specific aliases and functions
#
# cd upper levels
#
function cd {
    local option= length= count= cdpath= i=
# if we have -L or -P sym link option, save then remove it
    if [ "$1" = "-P" -o "$1" = "-L" ]; then
        option="$1"
        shift
    fi

    if [ -n "$1" -a "${1:0:3}" = '...' -a "$1" = "${1%/*}" ]; then
        length=${#1}
        count=2
        for ((i=$count;i<=$length;i++)); do
            cdpath="${cdpath}../"
        done
        builtin cd $option "$cdpath"
    elif [ -n "$1" ]; then
        builtin cd $option "$*"
    else
        builtin cd $option
    fi
}

#
# mkdir newdir then cd into it
#
function mcd {
    local newdir='_mcd_command_failed_'
    if [ -d "$1" ]; then
        echo "$1 exists..."
        newdir="$1"
    else
        if [ -n "$2" ]; then
            command mkdir -p -m $1 "$2" && newdir="$2"
        else
            command mkdir -p "$1" && newdir="$1"
        fi
    fi
    builtin cd "$newdir"
}

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export TERM=xterm-256color

# set cd path
export CDPATH=".:$HOME/workspace"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sl='ll | grep ">"'
alias l.='ls -dF .*'
[ "$OS" = "Linux" ] || alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias ec='emacsclient -c'
alias et='emacsclient -t'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
#alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

fi
