#!/bin/bash -eu
# local bash settings

echo Sourcing user bashrc ...

pathmunge () {
	if ! echo $PATH | /bin/egrep "(^|:)$1($|:)" >/dev/null ; then
	   if [ "$2" = "after" ] ; then
	      PATH=$PATH:$1
	   else
	      PATH=$1:$PATH
	   fi
	fi
}

cdn () { pushd .; for ((i=1; i<=$1; i++)); do cd ..; done; }

ctitle() {
    echo -ne "\033]0;$1\007"
}

[ $OS ] || OS=$(uname)

stty -ixon #-ixoff

# history
export HISTIGNORE=".1:.2:.3:.4:pwd:ls:l:la:ll:exit:quit:h:w:who:whoami:alias:which*:whereis*:cd:python*:emacs*:eclipse*:ps:v:vi:vim:envhost*:hostname:make:pstack*:pstree*:ifconfig*:jobs:fg:bg*:cal:date:locate:sleep*"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=1000
export HISTFILESIZE=5000

# extended globbing
shopt -s extglob

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Color definitions
COLORRC=$(dirname ${BASH_SOURCE[0]})/color.rc
[ -f $COLORRC ] && . $COLORRC

##################################
# prompt
#export PS1='\n=== \h [\D{%m-%d %a %H:%M:%S}] \w ===\n$ '
PS1="\n=\!=${Green}[\d \@] ${BIYellow}\u@\h:${White}\w\e[m ===\n\$ "


#########################################
# OS specific settings
#########################################
if [ $OS = SunOS ]; then
PATH=${PATH:+$PATH:}/usr/local/bin:/usr/ucb:/usr/openwin/bin:/usr/sfw/bin:/usr/ccs/bin:/usr/dt/bin${MRM_BIN:+:$MRM_BIN}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/openwin/lib:/usr/lib/X11:/usr/dt/lib:/usr/sfw/lib:/usr/ccs/lib:/usr/local/lib

# system limit
ulimit -S -c unlimited >&-

# Oracle
if [ $ARCH = "i386" ]; then
    export ORACLE_HOME=/opt/oratcp11/product/11.2.2
    pathmunge $ORACLE_HOME/bin
    LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
fi

# Java and Maven
if [[ $USER = *mso* ]] || [ $USER = rachen ]; then
    export JAVA_HOME=/usr/jdk/jdk1.6.0_95
    export M2_HOME=/opt/apps/algo2/algocredit-shared/apache-maven-3.2.2
    pathmunge $JAVA_HOME/bin
    pathmunge $M2_HOME/bin after
    export CLASSPATH=$M2_HOME/lib:$CLASSPATH
fi

# man path
export MANPATH=/usr/share/man:/usr/sfw/man:/usr/man:/usr/openwin/man:/apps/gnu/man:/apps/algo/perl/man

if [ $ARCH = "i386" ]; then
    MANPATH=$RAY_LOCAL/man:$MANPATH
fi

# git, this is only valid for scotiabank envs
pathmunge /home/alcrd2mso/git/bin after

elif [ "$OS" = Linux ]; then
# User specific aliases and functions
#
# cd upper levels
#
function cd {
    local option= length= count= cdpath= i=
# if we have -L or -P sym link option, save then remove it
    if [ "$1" = "-P" -o "$1" = "-L" ]; then
        option="$1"
        shift
    fi

    if [ -n "$1" -a "${1:0:3}" = '...' -a "$1" = "${1%/*}" ]; then
        length=${#1}
        count=2
        for ((i=$count;i<=$length;i++)); do
            cdpath="${cdpath}../"
        done
        builtin cd $option "$cdpath"
    elif [ -n "$1" ]; then
        builtin cd $option "$*"
    else
        builtin cd $option
    fi
}

#
# mkdir newdir then cd into it
#
function mcd {
    local newdir='_mcd_command_failed_'
    if [ -d "$1" ]; then
        echo "$1 exists..."
        newdir="$1"
    else
        if [ -n "$2" ]; then
            command mkdir -p -m $1 "$2" && newdir="$2"
        else
            command mkdir -p "$1" && newdir="$1"
        fi
    fi
    builtin cd "$newdir"
}

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
#if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
#    debian_chroot=$(cat /etc/debian_chroot)
#fi
#
## set a fancy prompt (non-color, unless we know we "want" color)
#case "$TERM" in
#    xterm-color) color_prompt=yes;;
#esac
#
## uncomment for a colored prompt, if the terminal has the capability; turned
## off by default to not distract the user: the focus in a terminal window
## should be on the output of commands, not on the prompt
##force_color_prompt=yes
#
#if [ -n "$force_color_prompt" ]; then
#    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
#	# We have color support; assume it's compliant with Ecma-48
#	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
#	# a case would tend to support setf rather than setaf.)
#	color_prompt=yes
#    else
#	color_prompt=
#    fi
#fi
#
## set up prompt
##export PS1='\n=== \h [\D{%m-%d %H:%M:%S}] \w ===\n$ '
#
#if [ "$color_prompt" = yes ]; then
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#else
#    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
#fi
#unset color_prompt force_color_prompt
#
## If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
#    ;;
#*)
#    ;;
#esac

# set cd path
export CDPATH=".:$HOME/workspace"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sl='ll | grep ">"'
alias l.='ls -dF .*'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
#alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

fi
